
-- ct_vecimg.sql: create stmnt, oracle, for project vector: images, vectors and search.

/*  */ 
drop table vec_img_vect ;
drop table vec_img ;
/* */

-- store image, just the jpg/blob and remarks.
-- consider attributes : img-type, img_size.. 
create table vec_img ( 
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_dt    date                default sysdate,
  fpath         VARCHAR2(255),
  fname         VARCHAR2(255),
  img_data      BLOB,
  remarks       VARCHAR2(255)
);

create table vec_img_vect (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_dt  date                 DEFAULT sysdate,
  img_id      number,             -- fk to img
  img_vector  VECTOR ( 2048, FLOAT32) ,
  gen_by      varchar2(255)        -- remarks on generation, model 
);

alter table vec_img_vect add constraint img_vec_fk_img foreign key ( img_id )
  references vec_img ( id ) ; 

