
-- oracle: demonstrate vector with few elements, store and calculate distances.

drop table dv1 ; 

create table dv1 (
  id    number generated by default as identity primary key
, vct   vector(3)
) ;

insert into dv1 (vct) values ('[1,2,3]'), ('[4,5,6]'), ('[1,1,1]');

column eucl_dist format 0.99999
column  cos_dist format 0.99999

SELECT id  
, vct
, vct <-> '[2,3,4]'  as eucl_dist
, vct <=> '[2,3,4]'  as cos_dist
FROM dv1 ORDER BY id ;


